// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaIWG4sWTlTLSe0NAC8jUgt1GxyneASL4',
    appId: '1:781563554652:web:f1627adbb321779452af99',
    messagingSenderId: '781563554652',
    projectId: 'breakbite-c33c3',
    authDomain: 'breakbite-c33c3.firebaseapp.com',
    storageBucket: 'breakbite-c33c3.firebasestorage.app',
    measurementId: 'G-D9J063G0MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2yBLTIpibvvmeAoYBaD0UCUP1UcRTBpo',
    appId: '1:781563554652:android:12ac27219925369c52af99',
    messagingSenderId: '781563554652',
    projectId: 'breakbite-c33c3',
    storageBucket: 'breakbite-c33c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmofDTtgXR9SyIEdR8Ek7yBj_RqHgSgC4',
    appId: '1:781563554652:ios:d97e79b20104f8d952af99',
    messagingSenderId: '781563554652',
    projectId: 'breakbite-c33c3',
    storageBucket: 'breakbite-c33c3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
